name: "Release action"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build code
        run: |
          npm install
          npm build
      - name: Commit and push
        run: |
          echo "git add -f lib/"
          git add -f lib/
          echo "git add -f node_modules/"
          git add -f node_modules/
          echo "committing files"
          git commit -m "[Automation]: Adding generated files - js files and node_modules"